export const images = {
  logo: "/images/logo.png",
  logoWhite: "/images/logo.png",
  hero: "/images/building1.png",
  frontGate: "/images/building2.png",
  manifesto: "/images/director.png",
  director: "/images/director.png",
  shooting: "/images/building3.png",
  chess: "/images/building1.png",
  integrity: "/images/building2.png",
  competence: "/images/building3.png",
  emotions: "/images/building1.png",
  autonomous: "/images/building2.png",
  teachers: "/images/director.png",
  character: "/images/building1.png",
  safety: "/images/building2.png",
  gallery: [
    "/images/building1.png",
    "/images/building2.png",
    "/images/building3.png",
    "/images/building1.png",
    "/images/building2.png",
    "/images/building3.png",
  ],
  news: {
    investiture: "/images/building1.png",
    sports: "/images/building2.png",
    sharkTank: "/images/building3.png",
    poolParty: "/images/building1.png",
    starGazing: "/images/building2.png",
    stem: "/images/building3.png",
  },
  testimonials: {
    anju: "/images/director.png",
    agarwal: "/images/building1.png",
    thapar: "/images/building2.png",
    astha: "/images/building3.png",
    bhanwara: "/images/building1.png",
  },
  admissionBanner: "/images/building1.png",
};
